Pandas have 2 types; Series (for 1D col) and Dataframe (for 2D tables)

#every row gets an index
#dataframe has form of dictionary where each column is a key

In [2]:
import pandas as pd 


df = pd.read_csv("Animal_Dataset.csv") #loads in csv file into dataframe 
print(df)

                  Animal Height (cm) Weight (kg)             Color  \
0               Aardvark     105-130       40-65              Grey
1               Aardwolf       40-50        8-14      Yellow-brown
2       African Elephant     270-310   2700-6000              Grey
3           African Lion      80-110     120-250               Tan
4       African Wild Dog       75-80       18-36      Multicolored
..                   ...         ...         ...               ...
189                  Yak     140-160    500-1200      Brown, Black
190  Yellow-Eyed Penguin       60-65         1-3     Yellow, White
191            Yeti Crab    Up to 15   Up to 0.5      White, Hairy
192                Zebra     220-340     400-900      Black, White
193          Zebra Shark   Up to 330    Up to 32  Brown, Yellowish

    Lifespan (years)         Diet               Habitat  \
0              20-30  Insectivore  Savannas, Grasslands
1              10-12  Insectivore  Grasslands, Savannas
2              60-70    Herbivore      Savannah, Forest
3              10-14    Carnivore  Grasslands, Savannas
4              10-12    Carnivore             Savannahs
..               ...          ...                   ...
189            20-25    Herbivore             Mountains
190         Up to 20    Carnivore         Coastal Areas
191         Up to 20     Omnivore    Hydrothermal Vents
192            20-25    Herbivore            Grasslands
193            25-30    Carnivore           Coral Reefs

                 Predators Average Speed (km/h)              Countries Found  \
0            Lions, Hyenas                   40                       Africa
1          Lions, Leopards                24-30  Eastern and Southern Africa
2            Lions, Hyenas                   25                       Africa
3       Hyenas, Crocodiles                   58                       Africa
4            Lions, Hyenas                   56           Sub-Saharan Africa
..                     ...                  ...                          ...
189  Snow Leopards, Wolves                   24      Himalayas, Central Asia
190           Seals, Orcas                   25                  New Zealand
191         Not Applicable       Not Applicable                Pacific Ocean
192          Lions, Hyenas                   25                       Africa
193            Larger Fish                   20          Indo-Pacific region

    Conservation Status           Family Gestation Period (days)  \
0         Least Concern  Orycteropodidae                 210-240
1         Least Concern        Hyaenidae                      90
2            Vulnerable     Elephantidae                 640-660
3            Vulnerable          Felidae                  98-105
4            Endangered          Canidae                      70
..                  ...              ...                     ...
189       Least Concern          Bovidae                 215-280
190          Endangered     Spheniscidae                   80-90
191       Not Evaluated         Kiwaidae          Not Applicable
192       Least Concern          Equidae                 180-365
193          Endangered  Stegostomatidae                   10-25

    Top Speed (km/h) Social Structure Offspring per Birth
0                 40         Solitary                   1
1                 40         Solitary                 2-5
2                 40       Herd-based                   1
3                 80      Group-based       2-4 (usually)
4                 56      Group-based               10-12
..               ...              ...                 ...
189               24      Group-based               10-50
190               25         Solitary                   1
191   Not Applicable         Solitary      Not Applicable
192               25      Group-based                5-20
193               20         Solitary            Up to 25

[194 rows x 16 columns]

# Basic functions

In [ ]:
df.head()       #prints 1st 5 rows

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12

In [3]:
df.tail()       #print last 5 rows

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
200,Yak,140-160,500-1200,"Brown, Black",20-25,Herbivore,Mountains,"Snow Leopards, Wolves",24,"Himalayas, Central Asia",Least Concern,Bovidae,215-280,24,Group-based,10-50
201,Yellow-Eyed Penguin,60-65,1-3,"Yellow, White",Up to 20,Carnivore,Coastal Areas,"Seals, Orcas",25,New Zealand,Endangered,Spheniscidae,80-90,25,Solitary,1
202,Yeti Crab,Up to 15,Up to 0.5,"White, Hairy",Up to 20,Omnivore,Hydrothermal Vents,Not Applicable,Not Applicable,Pacific Ocean,Not Evaluated,Kiwaidae,Not Applicable,Not Applicable,Solitary,Not Applicable
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20
204,Zebra Shark,Up to 330,Up to 32,"Brown, Yellowish",25-30,Carnivore,Coral Reefs,Larger Fish,20,Indo-Pacific region,Endangered,Stegostomatidae,10-25,20,Solitary,Up to 25

In [ ]:
df.info()       #general info on dataframe

#object types don't have quotations (strings need quotations)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Animal                   205 non-null    object
 1   Height (cm)              205 non-null    object
 2   Weight (kg)              205 non-null    object
 3   Color                    205 non-null    object
 4   Lifespan (years)         205 non-null    object
 5   Diet                     205 non-null    object
 6   Habitat                  205 non-null    object
 7   Predators                205 non-null    object
 8   Average Speed (km/h)     205 non-null    object
 9   Countries Found          205 non-null    object
 10  Conservation Status      205 non-null    object
 11  Family                   205 non-null    object
 12  Gestation Period (days)  205 non-null    object
 13  Top Speed (km/h)         205 non-null    object
 14  Social Structure         205 non-null    object
 15  Offspring per Birth      205 non-null    object
dtypes: object(16)
memory usage: 25.8+ KB

In [ ]:
df.describe()       #probability stats of data

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
count,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205,205
unique,196,162,184,85,93,16,97,113,97,104,12,120,161,71,10,68
top,Blobfish,Up to 30,Up to 0.5,Various,10-15,Carnivore,Rainforests,Not Applicable,Not Applicable,Worldwide,Least Concern,Canidae,Not Applicable,Not Applicable,Solitary,1
freq,2,4,4,14,21,72,31,13,21,19,68,14,12,31,132,81

In [7]:
df.columns      #gives all columns

Index(['Animal', 'Height (cm)', 'Weight (kg)', 'Color', 'Lifespan (years)',
       'Diet', 'Habitat', 'Predators', 'Average Speed (km/h)',
       'Countries Found', 'Conservation Status', 'Family',
       'Gestation Period (days)', 'Top Speed (km/h)', 'Social Structure',
       'Offspring per Birth'],
      dtype='object')

In [ ]:
df.index        #gives row indices

RangeIndex(start=0, stop=205, step=1)

# Indexing by rows & cols

In [3]:
df["Animal"]        #returns all values in "Animal" col as a Series data structure

0                 Aardvark
1                 Aardwolf
2         African Elephant
3             African Lion
4         African Wild Dog
              ...
189                    Yak
190    Yellow-Eyed Penguin
191              Yeti Crab
192                  Zebra
193            Zebra Shark
Name: Animal, Length: 194, dtype: object

In [ ]:
set(df["Countries Found"])      #returns all unique value in "Countries Found"

{'Africa',
 'Africa, Asia, Americas',
 'Africa, Asia, Australia, Oceania',
 'Africa, Iran, India',
 'Amazon Basin',
 'Amazon Rainforest',
 'Americas',
 'Antarctica',
 'Arctic',
 'Arctic regions',
 'Arctic, Atlantic Ocean',
 'Arctic, North America',
 'Arctic, Subarctic',
 'Argentina',
 'Argentina, Chile',
 'Asia',
 'Asia (Southeast)',
 'Asia, Africa',
 'Asia, Australia',
 'Asia, Russia',
 'Asia, Tibet',
 'Atlantic Ocean, Gulf of Mexico',
 'Australia',
 'Australia, New Guinea',
 'Australia, New Zealand',
 'Australia, New Zealand, Tasmania',
 'Borneo',
 'Borneo, Malaysia',
 'Brazil, Southeastern Bahia',
 'Central Africa',
 'Central America',
 'Central Asia, South Asia, Middle East',
 'Central and South America',
 'Central and South Asia',
 'Central and West Africa',
 'China',
 'China, Nepal, Bhutan, India',
 'Deep-sea regions',
 'Democratic Republic of Congo',
 'Democratic Republic of Congo, Uganda',
 'East Africa',
 'Eastern Africa',
 'Eastern Africa, Horn of Africa',
 'Eastern Pacific (GalÃ¡pagos Islands)',
 'Eastern and Southern Africa',
 'Eurasia, North Africa, Americas',
 'Eurasia, North America, North Africa',
 'Europe',
 'Europe, Asia',
 'European Alps',
 'GalÃ¡pagos Islands',
 'Galápagos Islands',
 'Gibraltar, North Africa, Middle East',
 'Gulf of California, Mexico',
 'Himalayas, Central Asia',
 'India',
 'India, Bangladesh, Nepal',
 'India, Nepal, Bhutan',
 'India, Southeast Asia',
 'Indian Ocean, Western Pacific',
 'Indian subcontinent',
 'Indian, Pacific Oceans',
 'Indo-Pacific region',
 'Indonesia',
 'Indonesia, Malaysia',
 'Japan, China, North Korea',
 'Japan, China, Southeast Asia',
 'Kalahari Desert, Africa',
 'Madagascar',
 'Mexico',
 'Middle East',
 'Middle East, North Africa',
 'New Zealand',
 'North Africa',
 'North America',
 'North America, Europe, Asia',
 'North Atlantic, Arctic',
 'North Pacific',
 'North, Central, and South America',
 'Northern Australia',
 'Northern Hemisphere',
 'Oceans worldwide',
 'Pacific Ocean',
 'Papua New Guinea, Indonesia',
 'Siberia, Alaska',
 'South America',
 'South America, Asia',
 'South and Central America',
 'Southeast Asia',
 'Southeast Asia, Philippines',
 'Southeast Asia, South Asia',
 'Southeast Asia, South Asia, Indonesia',
 'Southern Australia',
 'Southwestern United States, Mexico',
 'Spain, Portugal',
 'Sub-Saharan Africa',
 'Sumatra',
 'Tasmania, Australia',
 'Tropical Central Tropical Africa',
 'Vietnam, Laos',
 'Western Australia',
 'Western Colombia',
 'Western Indian Ocean',
 'Worldwide'}

In [14]:
df[["Habitat", "Countries Found"]]        #returns all pairs of values in "Habitat" and "Country" col as another dataframe

                  Habitat              Countries Found
0    Savannas, Grasslands                       Africa
1    Grasslands, Savannas  Eastern and Southern Africa
2        Savannah, Forest                       Africa
3    Grasslands, Savannas                       Africa
4               Savannahs           Sub-Saharan Africa
..                    ...                          ...
200             Mountains      Himalayas, Central Asia
201         Coastal Areas                  New Zealand
202    Hydrothermal Vents                Pacific Ocean
203            Grasslands                       Africa
204           Coral Reefs          Indo-Pacific region

[205 rows x 2 columns]

In [17]:
df.iloc[169]     #index by row

Animal                       Tasmanian Tiger
Height (cm)                          100-130
Weight (kg)                            20-30
Color                           Yellow-brown
Lifespan (years)                         4-7
Diet                               Carnivore
Habitat                            Australia
Predators                    Humans, Dingoes
Average Speed (km/h)                   40-72
Countries Found                    Australia
Conservation Status                  Extinct
Family                          Thylacinidae
Gestation Period (days)              121-128
Top Speed (km/h)                       40-72
Social Structure                    Solitary
Offspring per Birth        1-4 (usually 2-3)
Name: 169, dtype: object

# Filtering

In [ ]:
df[df["Predators"]== "Lions, Hyenas"]        
#find all animals with "Lions, Hyenas" as predators

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12
27,Black Rhinoceros,132-180,"800-1,400","Gray, Black",35-50,Herbivore,"Grasslands, Forests","Lions, Hyenas",56,Eastern and Southern Africa,Critically Endangered,Rhinocerotidae,450-480,56,Solitary,1
43,Cheetah,70-90,20-72,Tan with Black Spots,10-12,Carnivore,"Grasslands, Savannas","Lions, Hyenas",112,"Africa, Iran, India",Vulnerable,Felidae,90-98,112,Solitary,3-5
86,Grevy's Zebra,130-160,350-450,"White, Black",20-30,Herbivore,Grasslands,"Lions, Hyenas",64,Eastern Africa,Endangered,Equidae,390-396,64,Herd-based,1
191,White Rhinoceros,1400-2300,1800-2500,Gray,40-50,Herbivore,Grasslands,"Lions, Hyenas",45,Eastern and Southern Africa,Near Threatened,Rhinocerotidae,240-300,45,Group-based,1-14
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20

In [ ]:
df[(df["Predators"]== "Lions, Hyenas") & (df["Diet"]!= "Herbivore")]        
#find all animals with "Lions, Hyenas" as predators and are not herbivores

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12
43,Cheetah,70-90,20-72,Tan with Black Spots,10-12,Carnivore,"Grasslands, Savannas","Lions, Hyenas",112,"Africa, Iran, India",Vulnerable,Felidae,90-98,112,Solitary,3-5

In [ ]:
df[df["Countries Found"].str.startswith("A")]
#finds animals from countries starting with A

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
6,Amazon Rainforest Frog,2-13,Up to 0.5,Various,4-17,Insectivore,Amazon Rainforest,"Birds, Snakes",0.1-1,Amazon Rainforest,Not Evaluated,Dendrobatidae,10-15,0.8,Solitary,Up to 40
11,Arctic Fox,25-30,2.5-9,White,3-6,Omnivore,Tundra,Polar Bears,60,Arctic regions,Least Concern,Canidae,52-60,60,Solitary,4-11
13,Asian Elephant,200-300,2000-5000,Grey,60-80,Herbivore,"Grasslands, Forests","Tigers, Leopards",40,Asia (Southeast),Endangered,Elephantidae,640-660,40,Herd-based,1
16,Australian Fur Seal,112-160,18-40,"Brown, Gray",14-17,Carnivore,Coastal Waters,"Sharks, Orcas",24-40,"Australia, New Zealand",Least Concern,Otariidae,300-350,24-40,Group-based,1
24,Bearded Dragon,Up to 60,Up to 600,Various,6-15,Omnivore,"Deserts, Woodlands","Birds, Snakes",40-64,Australia,Not Evaluated,Agamidae,40-70,40-64,Solitary,Up to 24
28,Blobfish,Up to 30,Up to 10,Pinkish-gray,Up to 100,Carnivore,Deep-sea,Not Applicable,Not Applicable,"Australia, New Zealand, Tasmania",Vulnerable,Psychrolutidae,Not Applicable,Not Applicable,Solitary,Not Applicable
43,Cheetah,70-90,20-72,Tan with Black Spots,10-12,Carnivore,"Grasslands, Savannas","Lions, Hyenas",112,"Africa, Iran, India",Vulnerable,Felidae,90-98,112,Solitary,3-5
52,Dhole,50-55,12-21,"Red, Brown",10-15,Carnivore,"Forests, Grasslands","Tigers, Leopards",56,Asia,Endangered,Canidae,60-63,56,Pack-based,4-8
53,Dingo,48-58,13-20,"Tan, Brown",10-15,Carnivore,"Grasslands, Forests","Humans, Dingoes",48-64,Australia,Least Concern,Canidae,63,48-64,Group-based,1-10
56,Echidna,30-45,2.5-6.5,"Brown, Tan",15-20,Insectivore,"Forests, Grasslands","Dingoes, Eagles",16-56,"Australia, New Guinea",Least Concern,Tachyglossidae,22-28,16-56,Solitary,1
57,Electric Eel,Up to 270,Up to 20,Grayish-brown,10-15,Carnivore,Amazon Basin,"Crocodiles, Jaguars",Not Applicable,Amazon Basin,Least Concern,Gymnotidae,10 weeks,4.8,Solitary,Thousands
58,Emperor Penguin,100,22-45,"Black, White",15-20,Carnivore,Antarctic,Leopard Seals,2-2.5,Antarctica,Near Threatened,Spheniscidae,62-66,9,Colony-based,1
59,Emperor Tamarin,23-26,300-400,"Black, White",10-15,Omnivore,Rainforests,"Snakes, Hawks",32,Amazon Rainforest,Least Concern,Callitrichidae,140-145,32,Group-based,1-2
63,Flying Fox,Up to 40,Up to 1.1,"Brown, Gray",15-23,Herbivore,Forests,Birds of Prey,40-50,"Asia, Australia",Least Concern,Pteropodidae,140-150,40-50,Group-based,1
89,Harp Seal,Up to 180,Up to 160,"Silver, Gray",20-35,Carnivore,"Arctic, Atlantic Ocean","Polar Bears, Orcas",19-22,"Arctic, Atlantic Ocean",Least Concern,Phocidae,335,28,Group-based,1
92,Horseshoe Crab,Up to 56,Up to 2.3,Brownish-gray,Up to 20 years,"Carnivore, Scavenger","Ocean Floor, Coastal Areas","Birds, Predatory Fish",0.8-1.6,"Atlantic Ocean, Gulf of Mexico",Vulnerable,Limulidae,2 weeks,Not Applicable,Solitary,Thousands
93,Hummingbird,7.5-13,2-20,Various,3-5,"Nectar, Insects",Americas,"Birds of Prey, Snakes",40-80,Americas,Least Concern,Trochilidae,13-22,80,Solitary,1-3
109,Lyrebird,80-100,0.9-1.2,"Brown, Black",15-20,Omnivore,Rainforests,"Birds of Prey, Dingoes",0.02-0.03,Australia,Least Concern,Menuridae,50-55,Not Applicable,Solitary,1
110,Lyrebird,77-100,0.85-1.1,"Brown, Grey",Up to 20,Omnivore,Forests,Birds of Prey,Not Applicable,Australia,Least Concern,Menuridae,50-55,Not Applicable,Solitary,1
118,Monitor Lizard,Up to 244,Up to 166,Varies,Varies,Carnivore,Various,"Birds, Snakes",Varies,"Africa, Asia, Australia, Oceania",Varies,Varanidae,Varies,Varies,Solitary,Varies
121,Narwhal,Up to 500,Up to 1600,"Gray, Mottled White",50-60,Carnivore,Arctic Waters,"Polar Bears, Orcas",45,Arctic,Near Threatened,Monodontidae,14-16 months,45,Solitary,1
127,Pangolin,30-100,2-40,"Brown, Yellowish",10-20,Insectivore,"Grasslands, Forests","Lions, Tigers",32,"Asia, Africa",Critically Endangered,Manidae,240-260,32,Solitary,1
128,Patagonian Mara,45-75,5.5-16,"Brown, Gray",5-10,Herbivore,Grasslands,"Foxes, Birds of Prey",30,"Argentina, Chile",Least Concern,Caviidae,75-80,30,Group-based,1-3
130,Pink Fairy Armadillo,9-15,Up to 120,Pink,4-8,Insectivore,Grasslands,"Foxes, Birds of Prey",Not Applicable,Argentina,Near Threatened,Chlamyphoridae,60-64,Not Applicable,Solitary,1
131,Pink Fairy Armadillo,12-15,Up to 0.1,Pinkish,4,Insectivore,Grasslands,"Birds, Canids",0.8,Argentina,Near Threatened,Dasypodidae,60-64,0.8,Solitary,1
132,Platypus,10-15,0.7-2.4,Brown,10-17,"Carnivore, Insectivore",Eastern Australia,"Foxes, Birds of Prey",3-7,Australia,Near Threatened,Ornithorhynchidae,10 days (in burrow),9,Solitary,1-3 (rarely 5)
133,Polar Bear,Up to 160,Up to 700,White,25-30,Carnivore,Arctic,Orcas,40,Arctic,Vulnerable,Ursidae,195-265,40,Solitary,1-2
139,Quokka,40-54,2.5-5,"Brown, Gray",5-10,Herbivore,"Scrublands, Forests","Foxes, Cats",24,Australia,Vulnerable,Macropodidae,25-30,24,Solitary,1
141,Red Kangaroo,140-180,18-95,"Brown, Red",Up to 23,Herbivore,Grasslands,"Dingoes, Eagles",56,Australia,Least Concern,Macropodidae,30-34,56,Group-based,1
146,Secretary Bird,100-150,2.3-4.5,"Black, Grey",10-15,Carnivore,"Grasslands, Savannas","Snakes, Lizards",24,Africa,Least Concern,Sagittariidae,42-46,32,Solitary,2
147,Serval,54-62,8-18,"Yellowish-Tan, Black",10-12,Carnivore,"Grasslands, Wetlands","Leopards, Hyenas",44,Africa,Least Concern,Felidae,54-72,44,Solitary,1
154,Snowy Owl,52-71,1.6-3.3,White,10-15,Carnivore,"Arctic, North America","Foxes, Wolves",80,"Arctic, North America",Least Concern,Strigidae,32-34,80,Solitary,3-11
169,Tasmanian Tiger,100-130,20-30,Yellow-brown,4-7,Carnivore,Australia,"Humans, Dingoes",40-72,Australia,Extinct,Thylacinidae,121-128,40-72,Solitary,1-4 (usually 2-3)
171,Thorny Devil,Up to 20,Up to 85,"Brown, Tan",5-20,Insectivore,"Desert, Scrublands","Birds, Snakes",0.16-0.32,Australia,Least Concern,Agamidae,Not Applicable,Not Applicable,Solitary,Not Applicable
173,Tibetan Mastiff,61-78,63-75,"Black, Brown, Gray",10-12,Omnivore,Human Dwellings,Not Applicable,45,"Asia, Tibet",Not Applicable,Canidae,58-82,45,Social groups,1-10
174,Tiger,108-133,100-390,"Orange, Black Stripes",10-15,Carnivore,Rainforests,"Humans, Leopards",28,"Asia, Russia",Endangered,Felidae,280-310,28,Solitary,1-4
178,Tsetse Fly,Up to 0.7,Up to 0.03,"Brown, Gray",Up to 28,Carnivore,Savannahs,Not Applicable,Not Applicable,Africa,Not Applicable,Glossinidae,Varies,Varies,Solitary,Varies
181,Uakari,46-56,2-3,"Bald, Red",10-15,Omnivore,Rainforests,"Jaguars, Snakes",20,Amazon Basin,Vulnerable,Pitheciidae,120-130,20,Group-based,1-6
182,Vampire Bat,Up to 9,Up to 0.05,Brown,8-12,Carnivore,"Caves, Forests","Hawks, Owls",24-40,Americas,Least Concern,Phyllostomidae,50-70,24-40,Colony-based,1
184,Vulture,Varies,Varies,"Black, Brown",Varies,Carnivore,Various,Not Applicable,Varies,"Africa, Asia, Americas",Varies,Accipitridae,Varies,Varies,Social groups,Varies
185,Walrus,Up to 3200,Up to 1200,Brown,40-50,Carnivore,"Arctic, Coastal Areas","Polar Bears, Orcas",40,"Arctic, Subarctic",Least Concern,Odobenidae,20-25,40,Group-based,Up to 200
187,Water Buffalo,200-300,300-1200,Dark Gray,20-25,Herbivore,"Grasslands, Wetlands","Tigers, Crocodiles",40,"Asia, Africa",Least Concern,Bovidae,240-270,40,Group-based,30-500
197,Wombat,84-118,20-35,"Brown, Gray",5-10,Herbivore,"Forests, Grasslands","Dingoes, Tasmanian Devils",20,Australia,Least Concern,Vombatidae,126-138,20,Solitary,1
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20

In [ ]:
df[df["Countries Found"].isin(["Africa", "Arctic"])]
#finds all animals from "Africa" and "Arctic"

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Africa,Least Concern,Orycteropodidae,210-240,40,Solitary,1
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
121,Narwhal,Up to 500,Up to 1600,"Gray, Mottled White",50-60,Carnivore,Arctic Waters,"Polar Bears, Orcas",45,Arctic,Near Threatened,Monodontidae,14-16 months,45,Solitary,1
133,Polar Bear,Up to 160,Up to 700,White,25-30,Carnivore,Arctic,Orcas,40,Arctic,Vulnerable,Ursidae,195-265,40,Solitary,1-2
146,Secretary Bird,100-150,2.3-4.5,"Black, Grey",10-15,Carnivore,"Grasslands, Savannas","Snakes, Lizards",24,Africa,Least Concern,Sagittariidae,42-46,32,Solitary,2
147,Serval,54-62,8-18,"Yellowish-Tan, Black",10-12,Carnivore,"Grasslands, Wetlands","Leopards, Hyenas",44,Africa,Least Concern,Felidae,54-72,44,Solitary,1
178,Tsetse Fly,Up to 0.7,Up to 0.03,"Brown, Gray",Up to 28,Carnivore,Savannahs,Not Applicable,Not Applicable,Africa,Not Applicable,Glossinidae,Varies,Varies,Solitary,Varies
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20

In [ ]:
df.loc[df["Animal"]== "Naked Mole Rat"]
#pulls up location and data of "Naked Mole Rat"

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
120,Naked Mole Rat,Up to 9,Up to 80,"Pink, Wrinkled",Up to 32,"Herbivore, Insectivore",Underground Tunnels,"Snakes, Humans",0.03-0.08,East Africa,Least Concern,Heterocephalidae,70,Not Applicable,Eusocial,Up to 28

# Editing data

In [ ]:
df.loc[df["Animal"]== "Aardvark", "Countries Found"] = "Asia"
df.loc[df["Animal"]== "Aardvark"]

#changes countries found of aardvarks to asia (doesn't modify actual csv)

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
0,Aardvark,105-130,40-65,Grey,20-30,Insectivore,"Savannas, Grasslands","Lions, Hyenas",40,Asia,Least Concern,Orycteropodidae,210-240,40,Solitary,1

In [ ]:
df=df.drop(0)       #drops 1st row (not in actual csv file)
df.head()

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
1,Aardwolf,40-50,8-14,Yellow-brown,10-12,Insectivore,"Grasslands, Savannas","Lions, Leopards",24-30,Eastern and Southern Africa,Least Concern,Hyaenidae,90,40,Solitary,2-5
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
4,African Wild Dog,75-80,18-36,Multicolored,10-12,Carnivore,Savannahs,"Lions, Hyenas",56,Sub-Saharan Africa,Endangered,Canidae,70,56,Group-based,10-12
5,Alpine Ibex,67-101,19-120,Brown,15-20,Herbivore,"Mountains, Alpine","Wolves, Golden Eagles",56-64,European Alps,Least Concern,Bovidae,150,56-64,Group-based,1

# Analyzing data

In [ ]:
df["Countries Found"].value_counts()        
#counts how many times each countries' values pop up

Countries Found
Worldwide                               19
Central and South America               10
Australia                               10
Oceans worldwide                         8
Madagascar                               7
                                        ..
India, Southeast Asia                    1
Eurasia, North Africa, Americas          1
Eurasia, North America, North Africa     1
Northern Hemisphere                      1
Himalayas, Central Asia                  1
Name: count, Length: 104, dtype: int64

In [ ]:
df.sort_values("Countries Found", ascending= True)
#sorts values from alphabetical order of countries

,Animal,Height (cm),Weight (kg),Color,Lifespan (years),Diet,Habitat,Predators,Average Speed (km/h),Countries Found,Conservation Status,Family,Gestation Period (days),Top Speed (km/h),Social Structure,Offspring per Birth
203,Zebra,220-340,400-900,"Black, White",20-25,Herbivore,Grasslands,"Lions, Hyenas",25,Africa,Least Concern,Equidae,180-365,25,Group-based,5-20
2,African Elephant,270-310,2700-6000,Grey,60-70,Herbivore,"Savannah, Forest","Lions, Hyenas",25,Africa,Vulnerable,Elephantidae,640-660,40,Herd-based,1
3,African Lion,80-110,120-250,Tan,10-14,Carnivore,"Grasslands, Savannas","Hyenas, Crocodiles",58,Africa,Vulnerable,Felidae,98-105,80,Group-based,2-4 (usually)
147,Serval,54-62,8-18,"Yellowish-Tan, Black",10-12,Carnivore,"Grasslands, Wetlands","Leopards, Hyenas",44,Africa,Least Concern,Felidae,54-72,44,Solitary,1
146,Secretary Bird,100-150,2.3-4.5,"Black, Grey",10-15,Carnivore,"Grasslands, Savannas","Snakes, Lizards",24,Africa,Least Concern,Sagittariidae,42-46,32,Solitary,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,Dalmatian Dog,50-61,23-32,"White, Black",10-13,Omnivore,Worldwide,"Wolves, Birds of Prey",40-45,Worldwide,Not Applicable,Canidae,63,37,Pack-based,6-9
149,Shortfin Mako Shark,Up to 394,Up to 800,Metallic Blue,28-35,Carnivore,Oceans,Larger Sharks,45,Worldwide,Vulnerable,Lamnidae,20-24,45,Solitary,1
94,Humpback Whale,Up to 1700,Up to 30000,"Black, White",45-50,Omnivore,Oceans,Orcas,24-27,Worldwide,Least Concern,Balaenopteridae,365,24-27,Solitary,1
78,Goblin Shark,Up to 366,Up to 210,Pinkish-gray,30-35,Carnivore,Deep-sea,Not Applicable,Not Applicable,Worldwide,Data Deficient,Mitsukurinidae,Not Applicable,Not Applicable,Solitary,Not Applicable
23,Basking Shark,Up to 1100,400-700,"Gray, Brown",20-25,Carnivore,Oceans,"Orcas, Great White Sharks",14-28,Worldwide,Vulnerable,Cetorhinidae,36-42 months,14-28,Solitary,2-4